---
title: "Conclusions"
format: html
editor: visual
execute:
  echo: false
  warning: false
---

1.  Students are mostly enthusiastic about the library. They value it as a space and appreciate the help they receive. 
2.  There are some concerns about noise. We may want to clarify the proper sound level in parts of the library or work on making the quiet areas quieter. Since the color-coded room system is not well understood we might try to make the silent and quiet areas stand out more.
3.  Grad students have trouble coming to Watzek in person. We may want to establish more of a presence at the grad campus. 
4.   A considerable number of students are frustrated with a lack of access to full text and a considerable number are not familiar with ILL and/or Summit (20%). We should think about ways of increasing exposure to resource sharing.
5.  In some fields/classes multiple copies of textbooks on reserve might be useful.
6.  Both print and ebook formats are appreciated.
7.  The web site is now seven years old and could be ready for some updating.
