---
title: "Demographics"
editor: visual
execute:
  echo: false
  warning: false
format:
  html:
    code-fold: true
    code-summary: "Show the code"
---

```{r}
library(tidyverse)
library(kableExtra)
```

```{r}
userData<-read_csv("data/anonymizedData.csv")
```

```{r}
totalUsers<-nrow(userData)

```

#### Total respondants: `r totalUsers`.

#### By Year in School

```{r}
# year in school
userData %>% 
  group_by(yearInSchool) %>%
  summarize(count=n(), percent=round(count/totalUsers*100, 1)) %>%
  arrange(desc(count))%>%
  add_row(yearInSchool = "Total", count = totalUsers, percent = 100) %>%
  rename("Year in School"=yearInSchool) %>%
  kbl() %>%
  kable_styling()
```

#### By Major

```{r}
userData %>% 
  group_by(major) %>%
  summarize(count=n(), percent=round(count/totalUsers*100, 1)) %>%
  arrange(desc(count))%>%
  add_row(major = "Total", count = totalUsers, percent = 100) %>%
  rename("Major"=major) %>%
  kbl() %>%
  kable_styling()
```

By Division

```{r}
userData %>% 
  group_by(division) %>%
  summarize(count=n(), percent=round(count/totalUsers*100, 1)) %>%
  arrange(desc(count))%>%
  add_row(division = "Total", count = totalUsers, percent = 100) %>%
  rename("Division"=division) %>%
  kbl() %>%
  kable_styling()
```

By Campus

```{r}
userData %>%
  group_by(campus) %>%
  summarize(count=n(), percent=round(count/totalUsers*100, 1)) %>%
  arrange(desc(count))%>%
  add_row(campus = "Total", count = totalUsers, percent = 100) %>%
  rename("Campus"=campus) %>%
  kbl() %>%
  kable_styling()
  
```
