---
title: "Watzek Library User Survey, 2024"
format: html
editor: visual
execute:
  echo: false
  warning: false
---

```{r}
source("src/functions.R")
loadPackages()
```

## Background

During the academic year of 2023-4, members of Watzek Library staff developed and distributed a [survey](userSurvey.pdf){target="_blank"} to undergraduate and graduate students. The purpose was to gain feedback from students on Watzek Library resources, services, aspects of the building, and degree of helpfulness from staff.

Survey team members met periodically in the fall and early winter to brainstorm and refine questions. By late January, the final survey questions were posted to a Google Form.

## Survey Distribution

The survey was open from January 30th through February 18th. The survey was advertised via fliers, the Watzek newsletter, the Bark, the Grad School email list, and the IME list. Four random prizes of \$25 in flex points were made available to incentivise participation.

## Survey Team

-   Jim Bunnelle, Acquisitions/Collection Development Librarian

-   EJ Carter, Research & Instruction Librarian

-   Hannah Crummé, Head of Special Collections & College Archivist

-   Elaine Hirsch, Associate Director

-   Jen Jacobs (team lead), Associate Director for Collections and Access

-   Erica Jensen, Research & Instruction Librarian

-   Jeremy McWilliams, Head of Digital Services
