---
title: "12. Reseach tools and resources comments"
editor: visual
execute:
  echo: false
  warning: false
---

***Please share any comments about the research tools and resources listed above.***

The majority of comments on the final question, “Please share any comments about the research tools and resources listed above,” seemed influenced by the immediately preceding closed question about about format preferences. While a small number declared a positive preference for ebooks or print, more volunteered a more nuanced position, of which the following comments are representative:

> “I prefer to read real books but ebooks are better for finding things via search”

> “I love printed books but sometimes ebooks are easier”

> “Ebooks are more convenient but sometimes a physical copy is needed”

Several comments from graduate students suggested frustrations that are harder to mitigate. One, who is legally blind, suggested more availability of textbooks in audio format for greater accessibility. Others reported running into resources restricted to Boley, which may warrant reexamining the language users encounter in Primo in this scenario. Most responses to this final question, however, ranged from neutral (e.g., “Primo is great but the search function could be improved”) to positive, some of which were downright exuberant in their punctuation:

> “They're all very awesome.”

> “Primo has been a great resource for research in my graduate coursework.”

> “Love the resources”

> “I love primo. you guys should make primo merch.”

> “I really enjoy the databases such as Primo or Jstor”

> “I’m really grateful for the sheer number of resources we have!”

> “I LOVE THE RESOURCE LIBRARIANS!!!!!!!!!!!!!!!!!!!!!!!!!!!!”

> “Having Elaine come to my research class and showing us resources and tools for research was very helpful”

> “I love accessing articles online!!!”
