---
title: "15. Reseach frustrations"
editor: visual
execute:
  echo: false
  warning: false
---

***What frustrates you about doing research?***

Many students (126) expressed a number of frustrations about doing research, with repeated emphasis on discovering items without the full text appended and/or encountering paywalls. This recurring complaint might indicate that our deep journal cuts are having an impact on user attitudes and their ability to conduct research. Common concerns centered on the time-intensive nature of scholarly research, including approaching and scoping a topic, identifying and evaluating relevant sources, creating citations, and somewhat surprisingly, reading. Interface design was another common critique. The Watzek website and Primo were described by a senior as “great but clunky. It gets frustrating having to sign in through multiple portals just to get to one resource or article.”

Library instruction and research consultations should be helpful to students learning how to approach the research process more effectively; these are also opportunities for staff to acknowledge the time-consuming reality of an effective research experience. Although the Discovery Team meets monthly to adapt the Primo interface, it has been more than five years since there was any user testing and design rethinking of the library’s website. This could be a consideration for the future.
