---
title: "16. Comfort with library and staff"
editor: visual
execute:
  echo: false
  warning: false
---

```{r}
source("functions.R")
loadPackages()
userData<-read_csv("../data/anonymizedData.csv")
```

***Please indicate how much you agree with the following statements:***

### I feel welcome in Watzek Library

::: panel-tabset
## All Users

```{r}
comfortQuestion(userData, "agreeWelcomeInLibrary", "all users", "allWelcome.jpg", casOnly=FALSE, gradOnly=FALSE)

```

## Undergraduates

```{r}
comfortQuestion(userData, "agreeWelcomeInLibrary", "CAS users", "casWelcome.jpg", casOnly=TRUE, gradOnly=FALSE)
```

## Graduates

```{r}
comfortQuestion(userData, "agreeWelcomeInLibrary", "GRAD users", "gradWelcome.jpg", casOnly=FALSE, gradOnly=TRUE)
```
:::

### I feel comfortable asking questions of library staff

::: panel-tabset
## All Users

```{r}
comfortAskingQuestions(userData, "agreeComfortableAskingQuestions", "all users", "allAskingQuestions.jpg", casOnly=FALSE, gradOnly=FALSE)

```

## Undergraduates

```{r}
comfortAskingQuestions(userData, "agreeComfortableAskingQuestions", "CAS users", "casAskingQuestions.jpg", casOnly=TRUE, gradOnly=FALSE)
```

## Graduates

```{r}
comfortAskingQuestions(userData, "agreeComfortableAskingQuestions", "GRAD users", "gradAskingQuestions.jpg", casOnly=FALSE, gradOnly=TRUE)
```
:::
