---
title: "17. What do you value/suggest"
editor: visual
execute:
  echo: false
  warning: false
---

***What do you value the most about Watzek Library? If you could change one thing to make it a more welcoming place, what would it be?***

One hundred and twenty-nine students responded to the final open-ended question, and responses were overwhelmingly positive, with many mentioning multiple things they valued in a single response. Many students appreciated the architectural beauty of Watzek Library, with its windows and views mentioned frequently. Students valued the variety of seating areas within the library, including spaces for quiet reading and contemplation, the reservable study rooms, and spaces for group study and socialization. Some commented on this variety as being conducive to meeting different needs and preferences on different days. Library resources, helpful service from staff and student workers, library exhibits and programming, and 24/5 building access were also valued by respondents.

\

Suggested improvements included adding more comfortable seating throughout the library, providing spaces with softer lighting, soundproofing the study rooms, and adding a cafe. Students also requested increased access to outlets and additional cozy reading nooks.

Graduate students especially appreciated the delivery service, online textbooks, and streaming services, while noting the library’s location and lack of parking as deterrents to visiting the physical space.
