---
title: "9. Reseach tools relied upon"
editor: visual
execute:
  echo: false
  warning: false
---

***What other research tools do you rely on?***

*note: this is a summary of questions 9, 10, and 12*

Students were asked to rate the usefulness of four tools—Primo, library databases, Google, and Google Scholar—for starting a research project, and then were asked three open-ended questions about research. A dwindling minority of respondents engaged with these questions:

|                                                                                                   |               |
|---------------------------------------------------------------------------------------------------|---------------|
| What other research tools do you rely on?                                                         | 102 responses |
| Are there research tools or resources lacking in our collection that you would like to see added? | 83 responses  |
| Please share any comments about the research tools and resources listed above.                    | 54 responses  |

Across the three questions, “research tools and resources'' emerged as a nebulous category encompassing people, library services, and ancillary tools such as citation managers and guides. Among people, librarians were mentioned by the greatest number of respondents as valued resources. Faculty were directly mentioned almost as often; arguably, the assigned readings and textbooks that students reported relying on for research also represent faculty influence. Several students said they relied on peers, and two reported using networks or contacting an author to get what they needed. A number of responses repeated resources named in previous closed questions; Primo, the most popular of these, appeared in nine responses. Also named were PsycNet (in three comments), PsycVideos, Annual Reviews, PubMed, Project Muse, and SOAN resources. A handful of respondents mentioned books or bibliographies as essential to their research. Several students reported using other libraries. Surprisingly, the Internet Archive was mentioned by three respondents, while Wikipedia was named only once. A lone mention of SciHub was the only indication (or admission) of reliance on the dark web.

Of the 83 respondents to the question about tools or resources lacking in the collection, more than half (51) indicated that they saw no such gaps, with several expressing appreciation for having “thorough access to a lot of academic resources.” Some respondents named existing resources; several ideas were not clearly feasible, such as adding the Internet Archive. Within the realm of the feasible, commenters expressed interest in having access to APA PsycTests, more STEM resources, mental health journals, resources for school psychology, “a larger children’s fiction section for leisurely reading,” and a handful of even more specific resources. Access to “textbooks” came up three times, with one person expressing a wish for more copies of required course textbooks and another for more “e-textbooks for courses.” As above, it seems likely but not entirely clear that course reserves are indicated.

Several comments on this question imply a need for more instruction on how to use “the research resources.” One person suggested adding “a brief 101 on how best to use Primo search.” The number of resources erroneously named as unavailable—Science, Nature, JSTOR, the New York Times, Science Direct, Taylor & Francis, and loanable headphones—also suggests room for improvement in how we advertise and communicate about resources. One person complained about the level of access to Special Collections, “especially in regards to this History of our school as a colonial project.”

The majority of comments on the final question, “Please share any comments about the research tools and resources listed above,” seemed influenced by the immediately preceding closed question about about format preferences. While a small number declared a positive preference for ebooks or print, more volunteered a more nuanced position, of which the following comments are representative:

> I prefer to read real books but ebooks are better for finding things via search

> I love printed books but sometimes ebooks are easier

> Ebooks are more convenient but sometimes a physical copy is needed

Several comments from graduate students suggested frustrations that are harder to mitigate. One, who is legally blind, suggested more availability of textbooks in audio format for greater accessibility. Others reported running into resources restricted to Boley, which may warrant reexamining the language users encounter in Primo in this scenario. Most responses to this final question, however, ranged from neutral (e.g., “Primo is great but the search function could be improved”) to positive, some of which were downright exuberant in their punctuation:

> They're all very awesome.

> Primo has been a great resource for research in my graduate coursework.

> Love the resources

> I love primo. you guys should make primo merch.

> I really enjoy the databases such as Primo or Jstor

> I’m really grateful for the sheer number of resources we have!

> I LOVE THE RESOURCE LIBRARIANS!!!!!!!!!!!!!!!!!!!!!!!!!!!!

> Having Elaine come to my research class and showing us resources and tools for research was very helpful

> I love accessing articles online!!!
